Rollback Deployment added

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,9 +47,22 @@ jobs:
 
   # --- STAGE 2: Docker Build ---
   docker:
-    name: Containarization
+    name: Containarization & Image Push
     needs: [test-auth, test-backend] # ONLY runs if both test jobs pass
     runs-on: [self-hosted, dev]
+
+    strategy:
+      matrix:
+        service:
+          - name: auth
+            context: ./auth
+            image: inventory-auth
+          - name: backend
+            context: ./backend
+            image: inventory-backend
+          - name: frontend
+            context: ./frontend
+            image: inventory-frontend 
     steps:
       - name: Checkout Code
         uses: actions/checkout@v6
@@ -61,39 +74,17 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3    
-        
-      # --- Build Auth Image ---
-      - name: Build Auth Service
-        uses: docker/build-push-action@v6
-        with:
-          context: ./auth
-          #load: true # Pushes the image to the local Docker daemon
-          tags: ${{ vars.DOCKERHUB_USERNAME }}/inventory-auth:${{ github.sha }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-          push: true
+        uses: docker/setup-buildx-action@v3
 
-      # --- Build Backend Image ---
-      - name: Build Backend Service
+      - name: Build & Push ${{ matrix.service.name }}
         uses: docker/build-push-action@v6
         with:
-          context: ./backend
-          #load: true
-          tags: ${{ vars.DOCKERHUB_USERNAME }}/inventory-backend:${{ github.sha }}
+          context: ${{ matrix.service.context }}
+          tags: |
+            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.service.image }}:${{ github.sha }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-          push: true
-
-      # --- Build Frontend Image ---
-      - name: Build Frontend Service
-        uses: docker/build-push-action@v6
-        with:
-          context: ./frontend
           #load: true
-          tags: ${{ vars.DOCKERHUB_USERNAME }}/inventory-frontend:${{ github.sha }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
           push: true
 
       - name: Clean up unused Docker data
@@ -172,7 +163,7 @@ jobs:
           echo "Final Response: $RESPONSE"
           exit 1
 
-  # --- STAGE 5: k8s PROD Deployment ---
+  # --- STAGE 5: k8s PROD Deployment & Integration-Testing ---
   prod-deploy:
     name: PROD Deployment
     needs: dev-integration-testing
@@ -218,6 +209,7 @@ jobs:
     needs: prod-deploy
     runs-on: ubuntu-latest
     environment: PROD
+    continue-on-error: true
     steps:
       - name: prod Backend Deep Health Check
         run: |
@@ -243,5 +235,28 @@ jobs:
 
           echo "FAILURE: Backend health check timed out after 90s or reported unhealthy."
           echo "Final Response: $RESPONSE"
-          exit 1          
+          exit 1      
  
+  # --- STAGE 7: Undo PROD Deployments if Fails---   
+  prod-rollback:
+    name: PROD Rollback
+    needs: prod-integration-testing
+    if: failure()
+    runs-on: [self-hosted, dev]
+    environment: PROD
+
+    steps:
+      - name: Set Kubernetes Context
+        uses: azure/k8s-set-context@v4
+        with:
+          method: kubeconfig
+          kubeconfig: ${{ secrets.KUBECONFIG }}
+
+      - name: Rollback Auth Deployment
+        run: kubectl rollout undo deployment/auth
+
+      - name: Rollback Backend Deployment
+        run: kubectl rollout undo deployment/backend
+
+      - name: Rollback Frontend Deployment
+        run: kubectl rollout undo deployment/frontend     
